services:

  neo4j:
    image: neo4j:5.15
    container_name: infinity-db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./data/neo4j:/data

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: infinity-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  infinityengine:
    build:
      context: ./apps/infinityengine
      dockerfile: Dockerfile
    container_name: infinity-backend
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
      - kafka
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092

  web-ui:
    build:
      context: ./apps/web-ui
      dockerfile: Dockerfile
    container_name: infinity-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api
      - NEXT_PUBLIC_WS_URL=ws://localhost/infinity-ws

  nginx:
    image: nginx:latest
    container_name: infinity-proxy
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-ui
      - infinityengine

  prometheus:
    image: prom/prometheus:latest
    container_name: infinity-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - infinityengine

  grafana:
    image: grafana/grafana:latest
    container_name: infinity-grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus