global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'infinityengine'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['infinity-engine:8080']

  - job_name: 'neo4j'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['infinity-db:2004']